### ISSUE TITLE
Weird link behavior on the server commands page

### ISSUE THREAD

**Issue by steven1046** [OpenLiberty/openliberty.io#1211] opened 2019-06-05 21:46 UTC
Sometimes the links jump to the top of the same page instead of going to the intended server command:
1. Go to https://openliberty.io/docs/ref/command/#server-dump.html
2. Near the bottom click on server list
![image](https://user-images.githubusercontent.com/6392944/58992783-58c86500-87b1-11e9-8be4-c08870730d03.png)
3. Sometimes it jumps back up to the top of server dump instead of going to server list.
4. If it actually goes to server list, hit the browser back button and click on it again until the bug happens.

**Comment by ellenwyllie** [comment] 2019-09-26 15:32
I'm not able to recreate this issue. Do you still see this happening? @steven1046

**Comment by steven1046** [comment] 2019-09-26 15:38
@ellenwyllie I see it loading the right page when you click the links but sometimes it doesn't go back to the top.

**Comment by k8vance88** [comment] 2019-10-09 18:36
Closing because we haven't been able to reproduce

**Closed by k8vance88** 2019-10-09 18:36 UTC
Labels: bug
