### ISSUE TITLE
Revisit hotspot code fix #1190 and #1185

### ISSUE THREAD

**Issue by kinueng** [OpenLiberty/openliberty.io#1191] opened 2019-05-13 15:41 UTC
We rushed a fix into `master` via https://github.com/OpenLiberty/openliberty.io/pull/1190.  We are unsure why this fix resolved the problem with the code column.  The regression was caused by https://github.com/OpenLiberty/openliberty.io/pull/1185

### Please see for debug analysis from https://github.com/OpenLiberty/openliberty.io/pull/1190#issuecomment-491871209
> I have been trying to learn, on the fly, how all our hotspot code works. There are three guides that have broken right code columns due to a bug in our hotspot handling code. 1 of the 3 broken guides here
> https://openliberty.io/guides/microprofile-openapi.html
> 
> The variable `code_sections`[1] is suppose to store all the programming files needed by the guide. We use `code_sections` to highlight lines in certain files (files are referenced by a index number in `code_sections`). Somehow the `code_sections` variable is not completely loaded with all the files referenced by the guide and we get a console error [2]
> 
> [1]
> 
> https://github.com/OpenLiberty/openliberty.io/blob/c36831e21b0064fa49ccac07d9588b482c58c75b/src/main/content/_assets/js/guide-multipane.js#L12
> 
> [2]
> ![image](https://user-images.githubusercontent.com/31117513/57633906-ea093a80-7569-11e9-95a0-f3e7a48692f2.png)

### Justification for pushing the quick fix into `master` https://github.com/OpenLiberty/openliberty.io/pull/1190#pullrequestreview-236756215

> Approving this change so we can quickly get the guides working again on openliberty.io.
> 
> From my local testing, I did not encounter any code paths that would cause `$(this).data('file-index') === "undefined"`. It seems like this change makes the if statement NOOP, which suggests we can just delete the if block of code.
> 
> I wonder if this change was accidentally delivered and needs to be removed. For now, fixing the guides is higher priority and we can revisit this code to correct it if necessary.
> 
> I manually looked at some of the other static guides on our staging site, they seem to be fine with this fix.

**Comment by steven1046** [comment] 2019-08-07 15:02
I have found that the modified code is never executed, and since that is the case we can remove it since the guides are working as intended on openliberty.io. The original code looks like it was a patch to fix an underlying issue that has since been resolved by better marking of hotspots in the guides that it was trying to fix in the first place.

**Closed** 2019-08-14 18:00 UTC
