### ISSUE TITLE
New guides homepage design

### ISSUE THREAD

**Issue by kevinwlau** [OpenLiberty/openliberty.io#509] opened 2018-08-10 18:59 UTC
Redesigned guides homepage - with search, and expandable guides section
Latest updates here: https://ibm.box.com/s/71569ald8apgs5l57rc4x4m9fp2xzwg8

As of Aug 10, 2018:
All Guides - Guides Search, Guides page on load, Guides page expanded - August 2018
PNGS: https://ibm.box.com/s/ortt99sawvgkp1bf0928lxze6xi9l166
Redlines - https://ibm.box.com/s/aavu8q9l4rec23dd3qd2q9urbefxadyx

Assets
- Clouds 2x: https://ibm.box.com/s/5iz0t3plw1lf6fniw4drc08rd5fpetbg
- Clouds 1x: https://ibm.box.com/s/pohli3zdclux4ycmb33x45u9l6r8kp7b
- Search icon - https://ibm.box.com/s/ompdedsih0i8h9eokj1yyqe5ns4o9dqt

![image](https://user-images.githubusercontent.com/31117513/44042690-8531fdcc-9ee6-11e8-9986-dbad8aaee595.png)

**Comment by kinueng** [comment] 2018-08-31 20:48
Duplicate of #287

**Closed by kinueng** 2018-08-31 20:48 UTC
