### ISSUE TITLE
Exposing Tags on Blog Cards

### ISSUE THREAD

**Issue by mbroz2** [OpenLiberty/openliberty.io#1213] opened 2019-06-06 14:22 UTC
Under #1137 we are exposing tags for blogs, however, not on the blog 'cards' on /blog.  This issue is to determine if and if so, how a blog's tags should be exposed on the cards.

**Comment by mdenby** [comment] 2019-06-06 17:32
![Blog_Page Copy 2](https://user-images.githubusercontent.com/26823018/59053493-94216d00-885f-11e9-856c-685142882d46.jpg)
![Blog_Page Copy 3](https://user-images.githubusercontent.com/26823018/59053494-94216d00-885f-11e9-91fa-d6866396ab76.jpg)
![Blog_Page Copy 4](https://user-images.githubusercontent.com/26823018/59053495-94216d00-885f-11e9-8fca-a0be96b99211.jpg)
![Blog_Page Copy 5](https://user-images.githubusercontent.com/26823018/59053496-94216d00-885f-11e9-9f9d-e9732515b798.jpg)

**Comment by mdenby** [comment] 2019-06-07 18:52
I've moved the tags to the bottom, below the authors, the font size is smaller size (14px) on the desktop and tablet view. I've also included the redlines here.
![Blog_Page tags Final](https://user-images.githubusercontent.com/26823018/59126710-bc7a9b80-8933-11e9-9874-e02fa8940ea9.jpg)
 
![5_Blog_tags tablet](https://user-images.githubusercontent.com/26823018/59126747-cef4d500-8933-11e9-8557-f65d3146585e.png)
![Blog-Mobile](https://user-images.githubusercontent.com/26823018/59126755-d4521f80-8933-11e9-82f4-0f7f995cb418.png)

**Comment by mdenby** [comment] 2019-06-07 19:06
Redlines.

[Blog Tags Redlines.zip](https://github.com/OpenLiberty/openliberty.io/files/3267263/Blog.Tags.Redlines.zip)

**Comment by ellenwyllie** [comment] 2019-07-31 19:57
This is a duplicate of #1137. I opened a new issue (#1292) for displaying the tags on individual blog posts.

**Closed by ellenwyllie** 2019-07-31 19:57 UTC
Labels: enhancement
