### ISSUE TITLE
Feed broken

### ISSUE THREAD

**Issue by takakiyo** [OpenLiberty/openliberty.io#2055] opened 2021-03-13 09:07 UTC
https://www.openliberty.io/blog/ is up to date. But,
https://openliberty.io/blog/ has not been updated for a month.

Feed of this web site points documents on openliberty.io instead of www.openliberty.io,
so current feed information don't work.

**Comment by steven1046** [comment] 2021-03-24 18:20
@takakiyo do you mean the RSS feed or the list of blogs? Is it still out of sync for you?

**Comment by mbroz2** [comment] 2021-03-24 18:25
Please let us know if you're still seeing the issue.

**Comment by takakiyo** [comment] 2021-03-25 09:35
RSS feed is 'https://www.openliberty.io/feed.xml'. Yes, it is out of sync.

Please check https://openliberty.io/blog/
The latest post is 'Feb 10, 2021' on the blog list that has not 'www' in URL.
And, on https://www.openliberty.io/blog/ that HAS ’www', the latest post is 'Mar 24, 2021' now.

Please point 'www' pages in RSS feed of https://www.openliberty.io/feed.xml
   OR
sync https://openliberty.io/blog/ site with https://www.openliberty.io/blog/

**Comment by mbroz2** [comment] 2021-03-25 16:13
The issue regarding no updates since Feb 10th should be limited to the Asia region that is serviced by the Sydney datacenter and it not getting updated.  We're working with the cloud provider to resolve the issue.
It sounds like https://www.openliberty.io/blog/ is showing new content because it's being routed to a different datacenter, which is odd... as it should also be getting routed to the Sydney datacenter and be missing the content added after Feb 10th so we'll investigate that as well after we resolve the first issue.  That way, in the interim, you can use the www subdomain to obtain all the latest content.

**Comment by mbroz2** [comment] 2021-03-26 14:43
We have removed the Sydney servers from the load balancer as we continue to work with the cloud provider to fix the underlying issue.  This means that you should now see the latest content, but since it will be served up by either the Frankfurt or Dallas servers you may see some performance degradation until the Sydney servers are restored.

**Comment by mbroz2** [comment] 2021-03-26 14:55
I can confirm that the reason why www.openliberty.io worked is because that one routes the North East Asia region to Frankfurt, while openliberty.io routes that region to Sydney (which has issues currently that we're working on resolving)

**Comment by mbroz2** [comment] 2021-04-21 18:05
The feed should now be fixed (as of April 12th), as the Sydney server is back and has all the updates.

**Closed as completed by mbroz2** 2021-04-21 18:05 UTC
