### ISSUE TITLE
TOC closing when doc is selected in the Features section

### ISSUE THREAD

**Issue by Charlotte-Holt** [OpenLiberty/openliberty.io#1742] opened 2020-07-22 15:03 UTC
In the **Features** section of the navigation, when you click on **Differences between MicroProfile Fault Tolerance 1.x and 2.0**, the TOC closes. It should remain open so that users don't have to reopen it to find where they were. Also, if you click on any of the actual features, the TOC doesn't close, but it bumps users back up to the top of the **Features** section. It should remain in place so users aren't having to scroll back to where they were. I think this also applies to the **Server configuration** section.

**Comment by mbroz2** [comment] 2020-07-28 19:39
This occurs for:
https://openliberty.io/docs/20.0.0.7/reference/metrics-1-dif.html
https://openliberty.io/docs/20.0.0.7/reference/fault-tolerance-1-dif.html

**Comment by ellenwyllie** [comment] 2020-08-18 21:11
Reopening because #1809 fixes the issue with the toc scrolling back to the top after clicking on a feature doc, but it does not fix the issue related to metrics-1-dif.html and fault-tolerance-1-dif.html

**Comment by dmorgant** [comment] 2021-03-10 23:07
The following links do cause issues at the main website, but only at versions less than 20.0.0.11.
https://openliberty.io/docs/20.0.0.7/reference/metrics-1-dif.html
https://openliberty.io/docs/20.0.0.7/reference/fault-tolerance-1-dif.html

When either of these are selected 
- the doc appears without a Title
- the URL does not include **feature** as do the other Features when selected even though the breadcrumb does include it
-  the TOC  displays with the **Features** section closed and scrolled to the top.  When the **Features** section is expanded the doc is not highlighted in the TOC as one would have expected.  

![image](https://user-images.githubusercontent.com/29490139/110708718-b7a9e200-81c0-11eb-8f26-3100a0b28958.png)

It should be noted that these two docs do NOT appear alphabetically within the TOC (although this may have been done on purpose).

For versions 20.0.0.11 and greater, these 2 documents were removed from under **Features** and now appear under **Reference** directly:
![image](https://user-images.githubusercontent.com/29490139/110708482-5d108600-81c0-11eb-8157-460ec1614880.png)

---------------------------------------------------------------------

I discussed this issue with Steven and Katie.   The problem with the older versions of the two reference docs mentioned above is one issue.   The other issue left is that when something in the TOC is selected, the selected item is not scrolled into view within the TOC where the user can easily see it.  Instead the TOC is left scrolled to the top and the user has to scroll down to see their selection in the TOC.   For example, one would expect to see something like this when an item that had to be scrolled because it is further down on the page is selected:

![image](https://user-images.githubusercontent.com/29490139/110709770-597dfe80-81c2-11eb-8600-953116db19b5.png)

This does not always occur.  It seems to have been put in place for items appearing under **Features** (although it does not work for all Features), but not consistently for all TOC items, including those under **Deployment**, **Operations**, **Security**, etc..  Apparently, the expected behavior on the Antora website (see docs.antora.org) is for the TOC entry for the selected item to be scrolled into view as well as highlighted.

**Comment by dmorgant** [comment] 2021-03-11 15:07
This may also fix the problem described in #1878

**Comment by dmorgant** [comment] 2021-03-16 21:35
The fix for this done in PR #2056 fixes the 2nd issue described above.   Level 2 TOC items were not being correctly scrolled to in the TOC when selected because we were adjusting the height of the TOC after setting the scroll to amount.  

****   I have not been able to fix the issue with the links to https://openliberty.io/docs/20.0.0.7/reference/metrics-1-dif.html or https://openliberty.io/docs/20.0.0.7/reference/fault-tolerance-1-dif.html.  

In my local testing, antora is building the TOC differently so that multiple versions of a TOC item show up as separate entries with links to the different versions along the content top.   So, I am not seeing the problems getting to these 2 links locally.  It should be again noted that 
- for docs Version 10.0.0.11 and higher, these two doc appear under REFERENCE and **NOT** under REFERENCE>Features. Why the location change?  How do the location of the entries in the TOC get created?   For Version 20.0.0.10 and lower, the entries appear under Features, but not alphabetically positioned.
- while locally these pages display with a title for me, on the web site they do not.  So something about these entries are processed differently for me locally.
- the URL to these docs is of the form `docs/20.0.0.xx/reference/metrics-1-dif.html` ....with no` /features` in the URL.  So, how are these two docs positioned under the Features section?   

It seems like the code does not know where these menu items are in the TOC since the path to them in the TOC are not marked with the classes `is-active` and `is-current-path` (done in activateCurrentPath()). When entering into 01-nav.js, no TOC menu items (`nav-item`) have the 'is-current-page' class (line 15) so the menu panel's scrollTop is defaulted to 0....which is what we see.    However, this means we bypass going to activateCurrentPath() which is responsible for opening up all menu items down to the selected TOC entry.  Instead, the TOC menu is scrolled to the top and the REFERENCE and Features menu items are not expanded. 

I need to get more information on antora and how the TOC items are being created, along with what is setting the `is-current-page` class on a menu item when it is selected.

**Comment by dmorgant** [comment] 2021-04-07 16:20
Collectively we have decided to close this issue without fixing the indexing for the https://openliberty.io/docs/20.0.0.7/reference/metrics-1-dif.html or https://openliberty.io/docs/20.0.0.7/reference/fault-tolerance-1-dif.html as both of those documents now appear in a different location (right underneath the REFERENCE section) in versions 20.0.0.11 and above.

**Closed by dmorgant** 2021-04-07 16:20 UTC
Labels: bug
