### ISSUE TITLE
Blog page always refreshes to latest posts

### ISSUE THREAD

**Issue by navaneethsnair1** [OpenLiberty/openliberty.io#3507] opened 2023-12-01 14:41 UTC
When an older post is read by user and hit 'back', they won't be where they stopped before, but rather on the latest posts always.

**Comment by natalie-bernhard** [comment] 2024-04-24 13:17
We discussed that this was the intended behavior for this section of the blogs.  Closing this issue.

**Closed as completed by natalie-bernhard** 2024-04-24 13:17 UTC
