### ISSUE TITLE
Order of tabs should persist - Medium Priority

### ISSUE THREAD

**Issue by justineechen** [OpenLiberty/openliberty.io#873] opened 2019-01-11 18:07 UTC
The order of the tabs on the top of the right code panel changes. It should stay in the order they were introduced.

"I didn't like the fact that that order of the tabs on the right hand side changes with the focused one always on the left.  I felt I wanted them to behave like IDE tabs and always be in the order they were opened." - Feedback from Graham Charters

**Comment by steven1046** [comment] 2019-01-11 19:19
I agree that the order of tabs shouldn't change. Do we want to alphabetize them too or just keep it in the order introduced?

**Comment by steven1046** [comment] 2019-01-14 19:03
Duplicate of #876

**Comment by steven1046** [comment] 2019-01-15 20:34
Duplicate^

**Closed by steven1046** 2019-01-15 20:34 UTC
Labels: enhancement, multipane
