### ISSUE TITLE
Excessive white spacing for guide sections on Win 

### ISSUE THREAD

**Issue by salmad3** [OpenLiberty/openliberty.io#1693] opened 2020-06-12 23:02 UTC
### guide-getting-started
![image](https://user-images.githubusercontent.com/25497083/84552390-86a68a80-acde-11ea-88a2-4439ee7fc4ad.png)

---

### guide-docker
![image](https://user-images.githubusercontent.com/25497083/84552275-29aad480-acde-11ea-8000-c71883e78401.png)

![image](https://user-images.githubusercontent.com/25497083/84552299-4515df80-acde-11ea-9533-82330f6565d8.png)

---

### guide-microprofile-metrics
![image](https://user-images.githubusercontent.com/25497083/84552500-f74da700-acde-11ea-99cb-45537c2997d0.png)

**Comment by mbroz2** [comment] 2020-06-17 18:26
This is actually by design to separate the various sections from each other, and align them with the code on the right hand-side.  However, we'll look into this to see if there's any improvements that can be made.

**Comment by mbroz2** [comment] 2020-07-01 18:43
@mdenby what are you thoughts if we made the bottom of each section show the header for the next section, and make it clickable which would 'scroll' to that section (just like what happens if they click on that section in the ToC)?
For example:
![image](https://user-images.githubusercontent.com/3076261/86280139-dcb17400-bba0-11ea-8395-1acd55d8aa88.png)

**Comment by gkwan-ibm** [comment] 2020-07-07 19:33
@yeekangc

**Comment by yeekangc** [comment] 2020-07-07 19:50
It's quite a bit of scrolling in some cases like the below.  +1 that we should look into this.

<img width="1043" alt="image" src="https://user-images.githubusercontent.com/4803104/86835009-8abd9200-c069-11ea-9ac6-7331c35a9eb7.png">

**Comment by mdenby** [comment] 2020-07-07 20:35
Eeek--this is pretty weird spacing! So I see that there is a small amount of white space between headings and sections on the left that use the same code that appears on the right. And there is a large amount of space when the heading/code and the next heading/code are different...

The trigger for the code pane switching seems to be once the heading is about 3/4 up the page--regardless of the spacing above it. Can we just keep the spacing above each heading the same? I open to changing the trigger if it makes more sense to switch the code panel once the heading is scrolled higher on the page.

**Comment by mbroz2** [comment] 2020-07-08 00:28
I think the question is are we trying to address too much white space or too much scrolling?
If it's too much scrolling, then adding the next section to the bottom of the current section and making it clickable so that it 'auto-scrolls' to it (so same behavior we currently have for the ToC) may be enough to address the issue.

If we're trying to solve too much whitespace then that's more difficult.  If we try and have a set amount of vertical whitespace (less then the current 100% of the vertical viewport) then we'll have a problem for higher resolution screens (especially vertically) as they will show multiple sections at once and it will be impossible to know which section the user is on/reading and display the correct file in the right hand code pane.  
I believe this is the reason why the whitespace was designed to be there in the first place, to ensure that no more than one section was shown at any time in order to guarantee the correct files were shown in the code pane.

**Comment by gkwan-ibm** [comment] 2020-07-08 16:43
Is the spacing may cause the following problem?
- If my browser is longer enough, when I visit e.g. https://openliberty.io/guides/microprofile-reactive-messaging.html#creating-the-producer-in-the-system-microservice, the browser redirect me to the getting started section instead of the "Creating the producer in the system microservice" section

**Comment by mbroz2** [comment] 2020-07-08 16:55
I can't get it to 'redirect' me to a different section, but it does render incorrectly:
![image](https://user-images.githubusercontent.com/3076261/86947560-8a78d180-c111-11ea-9951-86277304acc5.png)
this is a bug that we should fix and it shouldn't have any impact on anything discussed in this issue (note that we have the correct behavior when the ToC is clicked, just not on load and that's what needs to be addressed for this bug).

**Comment by mbroz2** [comment] 2020-07-08 17:02
The above is true for Chrome, on Firefox, it does render the intended section even lower, causing the section above it to be scrolled to.  However, this is still the same bug and shouldn't impact what is being discussed in this issue.

**Comment by mbroz2** [comment] 2020-07-08 17:04
I've opened #1726 to address the improper scroll on load.

**Comment by yeekangc** [comment] 2020-07-09 16:42
Fwiw, I would say it's both a scrolling and a whitespace issue.  And, they likely feed each other from an end user standpoint.  I do feel this is a design/UX issue that we want to satisfactorily resolve regardless of the underlying technical root cause(s).

Thanks!  Cc @lauracowen.

**Comment by mbroz2** [comment] 2020-07-28 19:50
We're going to do what is outlined in https://github.com/OpenLiberty/openliberty.io/issues/1693#issuecomment-652585410

**Comment by mbroz2** [comment] 2020-07-28 19:53
@mdenby could you provide a design for the hover over styling/behavior of the section headers?

**Comment by mdenby** [comment] 2020-07-28 20:07
@mbroz2 Sure! (I plan on gathering all the open design issues and can prioritize this one)

**Comment by mbroz2** [comment] 2020-08-12 19:03
@mdenby any update on this one?

**Comment by mdenby** [comment] 2020-08-13 13:05
Last meeting when we talked about this, we decided to just reduce the white space enough to show the following section. This way the user knows there is another section to scroll down to see. I've posted an example here.

![Prerequisites](https://user-images.githubusercontent.com/26823018/90137748-0b943b80-dd44-11ea-9a7d-90024afeee7b.png)

**Comment by mbroz2** [comment] 2020-08-13 14:30
@mdenby the requested design was for the 'hover-over' behavior of the next header (to make it clear that it can be clicked).  My suggestion is the regular cursor change, plus a change in the border from the grey to maybe 'orange', similarly to what we want to do to highlight the prereq section in https://github.com/OpenLiberty/openliberty.io/issues/1701.  
If you agree, then I don't think we need anything else from design for this one.

**Comment by mdenby** [comment] 2020-08-13 14:37
I agree! :-)

**Comment by navaneethsnair1** [comment] 2024-04-30 04:37
@natalie-bernhard @steven1046  Isn't this issue closed already via another one? We don't seem to have excessive white spacing currently.

**Comment by steven1046** [comment] 2024-05-02 18:17
There is a lot of whitespace if you zoom out on the browser a lot (or have a really tall monitor vertically). It does look like the next section appears in view while at the top of a section:
<img width="1727" alt="image" src="https://github.com/OpenLiberty/openliberty.io/assets/6392944/b3427320-9bb5-446f-bec2-7a98695bb8cc">

so i think we can close this. Was there no PR linked that did this?

**Comment by natalie-bernhard** [comment] 2024-05-02 18:32
I think this issue's fix might've also resolved the issue: https://github.com/OpenLiberty/openliberty.io/issues/2270

**Closed** 2024-05-02 18:38 UTC
Labels: enhancement, good first issue
