### ISSUE TITLE
The related guides show up on top of the code pane

### ISSUE THREAD

**Issue by evelinec** [OpenLiberty/openliberty.io#1107] opened 2019-04-03 15:56 UTC
The related guides show up on top of the code content in the code pane, when scroll down to the bottom of the page: 

![image](https://user-images.githubusercontent.com/33134427/55493634-4db55500-5607-11e9-86da-3445792d2e2b.png)

**Comment by evelinec** [comment] 2019-04-03 15:57
@kinueng @steven1046

**Comment by mbroz2** [comment] 2019-04-03 19:20
@evelinec we're unable to reproduce this.  Can you comment on how this was achieved?

**Comment by steven1046** [comment] 2019-04-03 20:16
@mbroz2 @evelinec I believe the attached PR will fix this issue since after closing the back to text button and resizing to desktop the code was overflowing the end of the guide. That PR will fix that case, if it doesn't fix this problem then we can keep it open.

**Comment by evelinec** [comment] 2019-04-03 20:52
Ok, thanks @steven1046. We can verify when the PR is merged.

**Comment by steven1046** [comment] 2019-04-03 21:08
In 20 minutes, it will be fixed here: https://openlibertydev.mybluemix.net/guides/rest-intro.html

**Comment by evelinec** [comment] 2019-04-04 19:58
Looks good on the dev site. Also verified that it's refreshed on ol.io. Closed.

**Comment by evelinec** [comment] 2019-04-05 14:59
Reopen issue, as it can be reproduced on the ol.io site. 

The way I encountered the problem: 
1. Open a guide on ol.io site: https://openliberty.io/guides/microprofile-jwt.html
2. Minimize the browser to show single pane
3. Maximize the browser to show multi pane
4. Scroll all the way down to the bottom of the page
5. The related guides are on top of the code pane

**Comment by steven1046** [comment] 2019-04-05 15:00
Once the code is in master i'll close the issue

**Closed** 2019-04-18 19:50 UTC
Labels: bug

**Comment by evelinec** [comment] 2019-05-29 14:24
Verified the rest-intro guide with the steps. Looks good.
