### ISSUE TITLE
Scroll bar missing in the OpenLiberty guides page - Contents section.

### ISSUE THREAD

**Issue by dselvara1** [OpenLiberty/openliberty.io#2927] opened 2022-11-09 10:58 UTC
When I was trying to read through the instructions in the Liberty deepdive guide, noticed the vertical scroll bar is missing in the Contents section. As the guide is long, makes it difficult to traverse through different sections. Could not scroll even using the page up/down key. This is observed on windows - Chrome and Edge.

![image](https://user-images.githubusercontent.com/78403019/200811829-cd510c02-f1b1-46c3-8ddb-8ee053e04254.png)

**Comment by yeekangc** [comment] 2022-11-09 14:00
Cc @gkwan-ibm

**Comment by gkwan-ibm** [comment] 2022-11-09 14:32
it is a dup of #2914

**Comment by kinueng** [comment] 2023-03-22 15:06
Closing as this is a duplicate of issue https://github.com/OpenLiberty/openliberty.io/issues/2914

**Closed as completed by kinueng** 2023-03-22 15:06 UTC
Labels: duplicate
