### ISSUE TITLE
[Static/Interactive guides] Nav bar should fade away when scrolling down - Low Priority

### ISSUE THREAD

**Issue by steven1046** [OpenLiberty/openliberty.io#678] opened 2018-09-26 21:40 UTC
Nav scroll away and reappear.

**Comment by steven1046** [comment] 2019-02-22 17:41
I can't find any redlines/animations for the navbar dissapearing while scrolling, design do you know where they are located?

**Comment by mdenby** [comment] 2019-03-08 19:28
https://ibm.box.com/s/qeh1fso2dkowaiu8get98tualppsgji5

^^ Scrollable nav mockup can be seen in the 2nd half of this video (pls ignore the first half, has old navigation details)

**Comment by mbroz2** [comment] 2019-06-05 18:21
Duplicate of #1040

**Closed by mbroz2** 2019-06-05 18:21 UTC
Labels: enhancement
