### ISSUE TITLE
Changes needed for "RC" driver publishing

### ISSUE THREAD

**Issue by cbridgha** [OpenLiberty/openliberty.io#89] opened 2017-12-11 22:18 UTC
We have a release candidate ready to push for consumption by the downloads page, but when I add to the "releases" json, It is displayed at the top (before the existing release) and also auto changes the download buttons to point to this driver.

Because this is an RC driver, we want it available, but not considered a real "release", and should not be the default download.

I removed this entry from the json file until we work out our options.

**Comment by kinueng** [comment] 2017-12-11 22:41
The `retrieveBuildData` Java method handles how we currently handle the `info.json` when website is discovering the latest list of drivers.
https://github.com/OpenLiberty/openliberty.io/blob/master/src/main/java/io/openliberty/website/BuildsManager.java#L120

If we want to do any additional checks for release candidates, we can start from that method.

**Comment by gindik** [comment] 2017-12-12 15:06
When the Downloads page was designed, it was agreed that multiple releases could be made available. These would appear in the form of a table, sorted by date, most recent first by default. The main download buttons (in the website home page and the top of the Downloads page) would always point to the most recent release. On one hand it is good to see the site is behaving exactly as expected. On the other hand, it seems that requirements have changed from the moment the design work was done. From a technical point of view it would be fairly simple to accommodate the change as described above. One could, for example, agree on a variable called "default" in the build metadata that would indicate which release should be made available in the main download buttons. However, this could create confusion to the user as one would typically expect to obtain the latest release when clicking on the main download buttons. My suggestion would be to touch base with @NottyCode and/or the design team to see if perhaps a new table/category/decoration is needed to make these RC drivers clear and why they are not downloaded by default despite being labeled as "releases" and being the most recent ones.

**Comment by cbridgha** [comment] 2017-12-12 16:16
Thanks for your input @gindik - I agree at design time we did miss the requirement that RC drivers need to be published, but not handled the same as official release drivers.  I do like the behavior of the most recent releases being chosen as default, but somehow flagging these RC drivers so they are handled differently.

**Comment by kinueng** [comment] 2018-03-15 14:14
Hi @cbridgha,
Do we still have a need to show `RC` drivers?  I ask because of the 18001 build activities happening lately.

**Comment by cbridgha** [comment] 2018-03-15 14:39
Hi @kinueng yes - we need to followup, and maybe all we should do is "Mark" the nightly driver that is intended to be the RC - normally the "clone" driver is the RC, so we should always have the corresponding nightly already published.

**Comment by kinueng** [comment] 2018-06-29 17:14
We have some code to support displaying "Release Candidate" builds.  It looks like we did not get a chance to use the code for 18002, so we can try it for the next release candidate.

**Comment by kinueng** [comment] 2018-06-29 17:14
I will go ahead and close this issue.  The next time we want to display a release candidate, we will try and use the code we already delivered in #336

**Closed by kinueng** 2018-06-29 17:14 UTC
Labels: design needed
