### ISSUE TITLE
redesign bank website for circuit breaker to be consistent with the bulkhead bank website

### ISSUE THREAD

**Issue by aknguyen7** [OpenLiberty/openliberty.io#268] opened 2018-03-22 20:51 UTC
redesign for the following bank website for circuit breaker:

![image.png](https://images.zenhubusercontent.com/59dbe44ab0222d5de47af1b0/bbc74c42-02b1-4762-ba92-c9655618fe1c)

![image.png](https://images.zenhubusercontent.com/59dbe44ab0222d5de47af1b0/a0b39f1a-91d9-4542-9cc8-1ffab91984dd)

![image.png](https://images.zenhubusercontent.com/59dbe44ab0222d5de47af1b0/374aace2-1da8-42be-8386-f8db6c7a7966)

**Comment by aknguyen7** [comment] 2018-03-22 21:11
Jay'd like to keep track of the issue here

**Comment by dmorgant** [comment] 2018-03-23 19:39
Murphy has provided me with redesigned panels.  Implementing in the circuit breaker repository, under issue #94.  https://github.com/OpenLiberty/iguide-circuit-breaker/issues/94

**Comment by lavenal** [comment] 2018-03-27 19:15
I am closing this issue as the issue is tracked by the circuit-breaker guide. See Denise comment above.

**Closed by lavenal** 2018-03-27 19:15 UTC
Labels: design needed
